name: Python 3.10 (x86)

on: [push]

jobs:

  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
          architecture: x86

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run: poetry install

      - name: Run yapf
        run: poetry run yapf -r -d unlicense

      - name: Run mypy
        run: poetry run mypy --strict unlicense

      - name: Build PyInstaller package
        run: poetry run pyinstaller unlicense.spec

      - name: 'Upload PyInstaller Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: unlicense-py310-win32
          path: dist/*.exe
          retention-days: 3
